// ─── Image Generation Types ───
// تایپ‌های TypeScript برای سیستم تولید تصویر

export interface ImageProfile {
  id: string;
  name: string;
  instruction: string;
  negativePrompt: string;
  width: number;
  height: number;
  model: string;
  isBuiltin: boolean;
  createdAt: string;
}

export interface SceneImage {
  id: string;
  chatId: string;
  messageId?: string;
  profileId: string;
  llmPrompt: string;
  imagePrompt: string;
  negativePrompt: string;
  imageUrl: string;
  imageData?: string;
  model: string;
  seed: number;
  width: number;
  height: number;
  chapterId?: string;
  isAutoGenerated: boolean;
  isPinned: boolean;
  metadata: Record<string, any>;
  createdAt: string;
}

export interface CharacterPortrait {
  id: string;
  characterId: string;
  chatId?: string;
  profileId: string;
  llmPrompt: string;
  imagePrompt: string;
  negativePrompt: string;
  imageUrl: string;
  imageData?: string;
  model: string;
  seed: number;
  width: number;
  height: number;
  isCurrent: boolean;
  isVariation: boolean;
  parentId?: string;
  metadata: Record<string, any>;
  createdAt: string;
}

export interface ImageGenerationRequest {
  chatId?: string;
  characterId?: string;
  profileId: string;
  customPrompt?: string;
  width?: number;
  height?: number;
  model?: string;
}

export interface ImageGenerationResult {
  id: string;
  llmPrompt: string;
  imagePrompt: string;
  imageUrl: string;
  model: string;
  seed: number;
  width: number;
  height: number;
}

export interface ImageVariation {
  id: string;
  seed: number;
  imageUrl: string;
}

export interface PollinationsModel {
  id: string;
  name?: string;
  description?: string;
  input_modalities?: string[];
  output_modalities?: string[];
}

export interface ImagePreset {
  id: string;
  name: string;
  description: string;
  profileId: string;
  model: string;
  width: number;
  height: number;
  autoUseLastPrompt: boolean;
  promptTemplate: string;
  negativePrompt: string;
  isBuiltin: boolean;
  createdAt: string;
}

export type ImageType = 'scene' | 'portrait';

export interface ImageContextResult {
  context: string;
  profile: {
    id: string;
    name: string;
    instruction: string;
  };
}

export interface ImageControlsProps {
  image: SceneImage | CharacterPortrait;
  type: ImageType;
  onRegenerate: () => void;
  onVariations: () => void;
  onSave: () => void;
  onDelete: () => void;
  onViewPrompt: () => void;
}
